### ISSUE TITLE
linmos parsets are somehow already exist

### ISSUE THREAD

**Issue by tjgalvin** [tjgalvin/flint#15]
In my bulk processing I have noticed that some linmos tasks fail with an error like this:

```
Encountered exception during execution:
Traceback (most recent call last):
  File "/scratch3/gal16b/mambaforge/envs/flint/lib/python3.8/site-packages/prefect/engine.py", line 1719, in orchestrate_task_run
    result = await call.aresult()
  File "/scratch3/gal16b/mambaforge/envs/flint/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 292, in aresult
    return await asyncio.wrap_future(self.future)
  File "/scratch3/gal16b/mambaforge/envs/flint/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 316, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/scratch3/gal16b/packages/flint/flint/prefect/flows/continuum_pipeline.py", line 257, in task_linmos_images
    linmos_cmd = linmos_images(
  File "/scratch3/gal16b/packages/flint/flint/coadd/linmos.py", line 252, in linmos_images
    linmos_parset = generate_linmos_parameter_set(
  File "/scratch3/gal16b/packages/flint/flint/coadd/linmos.py", line 215, in generate_linmos_parameter_set
    assert not Path(
AssertionError: The parset /scratch3/gal16b/split/39404/linmos_round2_parset.txt already exists!
```

The code at this section is pretty straight forward

```
    # Now write the file, me hearty
    logger.info(f"Writing parset to {str(parset_output_name)}.")
    logger.info(f"{parset}")
    assert not Path(
        parset_output_name
    ).exists(), f"The parset {parset_output_name} already exists!"
    with open(parset_output_name, "w") as parset_file:
        parset_file.write(parset)

```

Looking at the parset on disk (which does exist) it is correct. And in all cases it does seem like linmos has run somewhere / somehow as the final products are there on disk.

**Comment by tjgalvin** [comment]
Slight tweak to 0341399b132423a7b9412b68c3248861bd7500af

I am really confused by this one. Even grepping all logs I see a single reference to the parset being written. So, if this run somehow did rerun the linmos twice, I should see it. Curious. 

I can always omit the assertion error, but I would rather understand this.

**Comment by tjgalvin** [comment]
Complete user error on this one. I reran the processing of an SBID already processed.
