### ISSUE TITLE
AegeanTools needs to be called through subprocess

### ISSUE THREAD

**Issue by tjgalvin** [tjgalvin/flint#6]
The prefect based continuum pipeline uses dask to establish a set of workers to carry out tasks concurrently. These dask workers are started in a daemon mode. 

In the current aegean branch there is a call into the `AegeanTools` infrastructure directly to run the components of `BANE` and the `aegean` source finder. However, at least `BANE` uses a multi-processing pool for acceleration. A multiprocessing pool can not be started by a process that is already running in a multiprocessing daemon mode. 

```
Encountered exception during execution:
Traceback (most recent call last):
  File "/scratch3/gal16b/mambaforge/envs/flint/lib/python3.8/site-packages/prefect/engine.py", line 1719, in orchestrate_task_run
    result = await call.aresult()
  File "/scratch3/gal16b/mambaforge/envs/flint/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 292, in aresult
    return await asyncio.wrap_future(self.future)
  File "/scratch3/gal16b/mambaforge/envs/flint/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 316, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/scratch3/gal16b/packages/flint/flint/prefect/flows/continuum_pipeline.py", line 57, in task_run_bane_and_aegean
    aegean_outputs = run_bane_and_aegean(image=image_path)
  File "/scratch3/gal16b/packages/flint/flint/source_finding/aegean.py", line 46, in run_bane_and_aegean
    BANE.filter_image(
  File "/scratch3/gal16b/mambaforge/envs/flint/lib/python3.8/site-packages/AegeanTools/BANE.py", line 487, in filter_image
    bkg, rms = filter_mc_sharemem(im_name,
  File "/scratch3/gal16b/mambaforge/envs/flint/lib/python3.8/site-packages/AegeanTools/BANE.py", line 375, in filter_mc_sharemem
    pool = ctx.Pool(processes=cores, maxtasksperchild=1,
  File "/scratch3/gal16b/mambaforge/envs/flint/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/scratch3/gal16b/mambaforge/envs/flint/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/scratch3/gal16b/mambaforge/envs/flint/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/scratch3/gal16b/mambaforge/envs/flint/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/scratch3/gal16b/mambaforge/envs/flint/lib/python3.8/multiprocessing/process.py", line 118, in start
    assert not _current_process._config.get('daemon'), \
AssertionError: daemonic processes are not allowed to have children
```

It is likely they way forward here is to use subprocess and run `BANE`/`aegean` from a spawned shell. Perhaps even put them in a container.

**Comment by tjgalvin** [comment]
This has been resolved. I ended up packaging aegean in its own singularity container and constructing a CLI command.
